# Avg_profiles Function

This function will compute the vertical profiles and the integral of u(z)*rho*C(z)

This function is called in the following notebooks:

    search_u_avg-2
    ...
    ...
    ...
    

In [53]:
import numpy as numpy 
#can't use np since that is used as a variable for length within the function

In [75]:
def avg_profiles(h,settl_vel,k,friction_coeff,uRhoAlpha_avg,rhoAlpha_avg,
                 u_guess,beta,h0,b,u_coeff,u_rel0):
    
    # The input here are the depth-averaged velocity and the depth-averaged
    # values of rho*C(z). We compute the vertical profiles and the integral of 
    # u(z)*rho*C(z), and we compare this value with the desired one to update
    # the average velocity.

    # Shear velocity computed from u_guess
    u_star = u_guess * sqrt(friction_coeff)

    # Rouse numbers for the particle classes
    Pn = settl_vel / ( k * u_star )

    # number of particle classes
    np = length(settl_vel)

    # array for depth-averaged value of rho*u(z)*C(z)
    rho_uAlpha = np.zeros(np)

    rhoAlpha_int = np.zeros(np)
    
    
    for i in range(0,np-1):

        a = -(0.6*Pn(i)*beta)/h 

        int = ( ( exp(a*h0) -1.0 )/a + exp(a*h0)*(h-h0) )/h 

        alpha_rel_max = 1.0/int 

        # relative concentration alpha_rel at depth h0 (from the bottom)
        # alpha_rel is defined as alpha(z)/alpha_avg
        alpha_rel0 = alpha_rel_max * exp(a*h0) 

        # depth-averaged value of rho*C(z)
        # this results from the sum of the log region with thickness h0 and the 
        # constant region with thickness h-h0
        rhoAlpha_int[i] = rhoAlpha_avg[i] * ( alpha_rel_max * ( exp(a*h0) - 1.0 ) / a + (h-h0)*alpha_rel0 ) / h   

        # we compute the integral in the log region of u_rel(z)*C_rel(z), where 
        # u_rel is defined as u(z)/(u_guess*u_coeff*sqrt(friction_coeff)) 
        y = h0 
        int_h0 = ( exp(a*y)*log(b*y+1.0) + exp(-a/b) * expint( -a*(y+1.0/b) ) ) / a 
        y = 0 
        int_0 = ( exp(a*y)*log(b*y+1.0) + exp(-a/b) * expint( -a*(y+1.0/b) ) ) / a 

        # integral of u_rel(z)*C_rel(z) in the log region (0<=z<=h0)
        int_def = u_coeff * sqrt(friction_coeff) / k * alpha_rel_max * (int_h0-int_0) 

        # we add the contribution of the integral of the constant region, we
        # average by dividing by h and we multiply by the density of solid and
        # average concentration
        rho_uAlpha[i] = rhoAlpha_av[i] * ( int_def + ( h - h0 ) * alpha_rel0 * u_rel0 ) / h 


    rhoAlpha_new_avg = sum(rhoAlpha_int) 
    rho_uAlpha_new_avg = sum(rho_uAlpha) 

    u_new_avg = uRhoAlpha_avg / ( rho_uAlpha_new_avg) 
    rho_uAlpha_new_avg = u_new_avg * rho_uAlpha_new_avg 
    
    return([u_new_avg,rhoAlpha_new_avg,rho_uAlpha_new_avg])



In [68]:
# Testing syntax 

def test(x):
    x = x**2
    return([x,(x+1)])

test(4)
#  variables need to be written to within the function 

[16, 17]

In [74]:
q = 5
print(numpy.zeros(q))
empty_vector = numpy.zeros(q)
empty_vector[0] = 1
print(empty_vector)

[0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0.]


In [57]:
np = 3
rho_uAlpha = numpy.zeros((1,3))
rhoAlpha_int = numpy.zeros(np)

In [58]:
numpy.zeros((2, 1))

array([[0.],
       [0.]])